### ISSUE TITLE
NoClassDefFoundError when bootstrap silently ignores packages with the same name in different jars

### ISSUE THREAD

**Issue by ChampionAsh5357** [McModLauncher/bootstraplauncher#9]
## Description

When bootstrap loads a jar on the legacy classpath into its associated module layer, it pulls only packages that were not previously present in other, already loaded jars. If there are class files in both packages under the same name in separate modules, then the later package will be removed from the classpath, barring any usage from the removed class.

```
module A
    - package X
        - class I
        - class J
module B
    - package X // This package will not be loaded, preventing usage of R, S, T
        - class R
        - class S
        - class T
```

This typically does not cause any issues as most organizations tend to properly subdivide their libraries into separate groups such that packages are never duplicated. However, there are a few which take extra care to avoid conflicts, but still use the same packaging across different jars, forcing this issue to occur.

## Example

Scala 3's library artifact is implemented in an uncommon way. Scala 3 requires the Scala 2 library as a dependency to use the common classes implemented, as a method of interoperability between major versions, while anything new is added in the Scala 3 library. The standard libraries within these artifacts are located in the `scala` package. As such, most of the Scala 2 standard library is unable to be accessed, throwing a `NoClassDefFoundError`.

Scala 3 library: `org.scala-lang:scala3-library_3:3.2.0`
Scala 2 library: `org.scala-lang:scala-library:2.13.8`

> There are a number of other classes within the scala libraries that share the same packages, but for the purposes of this explanation, we will only mention one.

You can view an implementation of the issue [here](https://github.com/ChampionAsh5357/Minecraft-Multlingual-Examples/tree/1.19.x/forge/forge-scala). This will throw a `NoClassDefFoundError` for `scala.Option` as it was removed by bootstrap due to the scala 3 library module being loaded first.

## Further Work

If bootstraplauncher chooses to not fix the issue, then there needs to be some reporting when a package is removed which contained associated classes, or simply crash if two classes contain the same package with class files within them. I only discovered the issue due to some help from @SizableShrimp who knew some inner workings of ForgeGradle and the mod launcher.

**Comment by LexManos** [comment]
This is intentional design due to Java's Module system not allowing multiple modules with the same package.
You can flip the [debug flag](https://github.com/McModLauncher/bootstraplauncher/blob/main/src/main/java/cpw/mods/bootstraplauncher/BootstrapLauncher.java#L37) to see which modules get which package.
You can work around this by specifying the [merge map](https://github.com/McModLauncher/bootstraplauncher/blob/09c1f9980369e01724d6e8842c23dcf8a53fb46d/src/main/java/cpw/mods/bootstraplauncher/BootstrapLauncher.java#L145).
We also automatically merge legacy libraries based on their [module name](https://github.com/McModLauncher/bootstraplauncher/blob/09c1f9980369e01724d6e8842c23dcf8a53fb46d/src/main/java/cpw/mods/bootstraplauncher/BootstrapLauncher.java#L88). So you could work with that to make them auto-merge.
Until such time as whatever library set you're loading is module aware. You may have to modify it to make it function properly with the module system.

**Comment by SizableShrimp** [comment]
Note that merge modules is only a valid solution inside of dev for userdev mods. As mods don't exist early enough in production to do this. So you would probably need to do shading shenanigans to fix it in production, and JIJ would probably fail (although you can use both together if you know what you're doing).
